server:
  port: 9000
spring:
  cloud:
    gatway:
      routes:
        - id: USER-SERVICE
          uri: http://localhost:8090
          predicates:
            - Path= /users/**
        - id: DEPARTMENT-SERVICE
          uri: lb://DEPARTMENT-SERVICE
          predicates:
            - Path= /departments/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka
  instance:
    hostname: localhost
